// Fallback breed data for when Supabase is unavailable
export const fallbackBreeds = [
  {
    breed: "Labrador Retriever",
    group: "Sporting",
    min_height: 55,
    max_height: 62,
    min_weight: 25,
    max_weight: 36,
    min_expectancy: 10,
    max_expectancy: 12,
    energy_level_value: 0.8,
    trainability_value: 0.9,
    description: "Friendly, outgoing, and active companions who have more than enough affection to go around for a family looking for a medium to large dog."
  },
  {
    breed: "Golden Retriever",
    group: "Sporting",
    min_height: 51,
    max_height: 61,
    min_weight: 25,
    max_weight: 34,
    min_expectancy: 10,
    max_expectancy: 12,
    energy_level_value: 0.7,
    trainability_value: 0.9,
    description: "Friendly, intelligent, and devoted dogs that are excellent family pets."
  },
  {
    breed: "German Shepherd",
    group: "Herding",
    min_height: 55,
    max_height: 65,
    min_weight: 22,
    max_weight: 40,
    min_expectancy: 9,
    max_expectancy: 13,
    energy_level_value: 0.8,
    trainability_value: 0.9,
    description: "Confident, courageous, and smart working dogs that are extremely versatile."
  },
  {
    breed: "French Bulldog",
    group: "Non-Sporting",
    min_height: 28,
    max_height: 33,
    min_weight: 8,
    max_weight: 14,
    min_expectancy: 10,
    max_expectancy: 12,
    energy_level_value: 0.4,
    trainability_value: 0.6,
    description: "Playful, alert, adaptable, and completely irresistible companions."
  },
  {
    breed: "Bulldog",
    group: "Non-Sporting",
    min_height: 31,
    max_height: 40,
    min_weight: 18,
    max_weight: 25,
    min_expectancy: 8,
    max_expectancy: 10,
    energy_level_value: 0.3,
    trainability_value: 0.5,
    description: "Docile, willful, and friendly companions with a laid-back attitude."
  },
  {
    breed: "Poodle",
    group: "Non-Sporting",
    min_height: 38,
    max_height: 60,
    min_weight: 20,
    max_weight: 32,
    min_expectancy: 10,
    max_expectancy: 18,
    energy_level_value: 0.7,
    trainability_value: 0.9,
    description: "Exceptional intelligence and trainability make Poodles highly adaptable and excellent companions."
  },
  {
    breed: "Beagle",
    group: "Hound",
    min_height: 33,
    max_height: 41,
    min_weight: 9,
    max_weight: 16,
    min_expectancy: 10,
    max_expectancy: 15,
    energy_level_value: 0.6,
    trainability_value: 0.6,
    description: "Loving, lovable, and happy dogs that make excellent family companions."
  },
  {
    breed: "Rottweiler",
    group: "Working",
    min_height: 56,
    max_height: 69,
    min_weight: 35,
    max_weight: 60,
    min_expectancy: 9,
    max_expectancy: 10,
    energy_level_value: 0.6,
    trainability_value: 0.8,
    description: "Confident, fearless, and good-natured companions and guardians."
  },
  {
    breed: "Yorkshire Terrier",
    group: "Toy",
    min_height: 18,
    max_height: 23,
    min_weight: 2,
    max_weight: 3,
    min_expectancy: 11,
    max_expectancy: 15,
    energy_level_value: 0.6,
    trainability_value: 0.6,
    description: "Feisty, brave, and sometimes bossy, Yorkies exhibit all the traits of a true terrier."
  },
  {
    breed: "Dachshund",
    group: "Hound",
    min_height: 20,
    max_height: 27,
    min_weight: 5,
    max_weight: 15,
    min_expectancy: 12,
    max_expectancy: 16,
    energy_level_value: 0.5,
    trainability_value: 0.5,
    description: "Friendly and spunky, Dachshunds are bred for persistence, which is another way of saying they can be stubborn."
  }
];